query getCastleGateWarehouseShippingAdvice($limit: Int32, $hasResponse: Boolean, $fromDate: IsoDateTime, $wsaIds: [String], $sortOrder: SortOrder){
    getCastleGateWarehouseShippingAdvice(limit: $limit, hasResponse: $hasResponse, fromDate: $fromDate, wsaIds: $wsaIds, sortOrder: $sortOrder){
        wsaId
        supplierId
        poNumber
        fulfillmentCustomerOrderNumber
        fulfillmentCustomerId
        retailerOrderNumber
        fulfillmentPurchaseOrderNumber
        creationDate
        shipDate
        shipSpeed
        carrierCode
        totalShipmentWeight
        totalQuantity
        clientNumber
        warehouseId
        actionDate
        transactionHandle
        packages{
            packageWeight
            trackingNumber
        }
        shipFrom{
            name
            title
            company
            address1
            address2
            address3
            city
            state
            country
            postalCode
            phoneNumber
        }
        shipTo{
            name
            title
            company
            address1
            address2
            address3
            city
            state
            country
            postalCode
            phoneNumber
        }
        products{
            quantityOrdered
            partNumber
            name
            quantityShipped
            upc
            sku
            forceQuantityMultiplier
        }
    }
}