query getCastleGatePurchaseOrders($limit: Int32, $hasResponse: Boolean, $fromDate: IsoDateTime, $poNumbers: [String], $sortOrder: SortOrder){
    getCastleGatePurchaseOrders(limit: $limit, hasResponse: $hasResponse, fromDate: $fromDate, poNumbers: $poNumbers, sortOrder: $sortOrder){
        id
        storePrefix
        poNumber
        poDate
        orderId
        estimatedShipDate
        scheduledDeliveryDate
        deliveryMethodCode
        customerName
        customerAddress1
        customerAddress2
        customerCity
        customerState
        customerPostalCode
        customerCountry
        customerEmail
        salesChannelName
        orderType
        shippingInfo{
            shipSpeed
            carrierCode
            poolPointAgent{
                id
                name
            }
            crossDockAgent{
                id
                name
            }
            deliveryAgent{
                id
                name
            }
        }
        packingSlipUrl
        warehouse{
            id
            name
            address{
                name
                address1
                address2
                address3
                city
                state
                country
                postalCode
                phoneNumber
            }
            supplier{
                id
                name
                shortName
                status
                websiteURL
                currency
                scopes{
                    id
                    name
                    permissionName
                    description
                }
                warehouses{
                    id
                    name
                    address{
                        name
                        address1
                        address2
                        address3
                        city
                        state
                        country
                        postalCode
                        phoneNumber
                    }
                    supplier{
                        id
                        name
                        shortName
                        status
                        websiteURL
                        currency
                    }
                }
            }
        }
        products{
            partNumber
            quantity
            price
            pieceCount
            totalCost
            name
            weight
            totalWeight
            estShipDate
            fillDate
            sku
            isCancelled
            isTscaCompliant
            twoDayGuaranteeDeliveryDeadline
            event{
                id
                type
                name
                startDate
                endDate
            }
            customComment
        }
        shipTo{
            name
            address1
            address2
            address3
            city
            state
            country
            postalCode
            phoneNumber
        }
        billTo{
            name
            address1
            address2
            address3
            city
            state
            country
            postalCode
            phoneNumber
        }
        billingInfo{
            vatNumber
        }
    }
}